### ISSUE TITLE
XML Link Not Working

### ISSUE THREAD

**Issue by 4d7568616d6d6564** [patrykandpatryk/vico#1125]
### Area

Not working.  I'm looking for an advanced example with XML and Kotlin, but everything is very complex and everything is done in Compose. The link below doesn't work. Can you give me a complete example for XML? For example, what would a cubic line look like, or what would a gradient color look like?

https://www.patrykandpatrick.com/vico/guide/stable/android/learning-resources#sample-app

### Error

Not working.  I'm looking for an advanced example with XML and Kotlin, but everything is very complex and everything is done in Compose. The link below doesn't work. Can you give me a complete example for XML? For example, what would a cubic line look like, or what would a gradient color look like?

**Comment by Gowsky** [comment]
Hello, @4d7568616d6d6564. Thanks for the report. The links have been fixed. 

> everything is very complex and everything is done in Compose

Basic examples are available in the guide and the sample app. All examples and documentation have versions for both Compose and the view system.

**Comment by 4d7568616d6d6564** [comment]
@Gowsky Could you give me a full XML example? For example, I would be very grateful if you could provide a fully controllable example using XML and Kotlin, such as how to do gradients, pointer markers, font changes, whether text will be displayed on top or bottom, and how to make the grid visible and change its color.

**Comment by Gowsky** [comment]
Please check the sample app, as it uses XML styles for the charts. You can also refer to the documentation, the source code, or ask some specific questions in the discussions category.

**Comment by 4d7568616d6d6564** [comment]
<img width="661" height="416" alt="Image" src="https://github.com/user-attachments/assets/5a1376a9-b442-44ac-bad4-bb7b4bdd3d6e" />

still not working this page

**Comment by Gowsky** [comment]
This is the correct [link](https://www.patrykandpatrick.com/vico/guide/stable/learning-resources#api-reference).

**Comment by 4d7568616d6d6564** [comment]
@Gowsky but I look at the views section and all the examples are written as @compsable

https://github.com/patrykandpatrick/vico/blob/v2.1.3/sample/views/src/main/kotlin/com/patrykandpatrick/vico/sample/views/BasicLineChart.kt

**Comment by Gowsky** [comment]
The sample app is made in Compose. Thus, Compose is the host of the view. Here, `AndroidViewBinding` inflates the XML layout resource and returns its binding. All modifications of the chart view are made using the standard `android.view.View`–style APIs and don't involve Compose.

**Comment by 4d7568616d6d6564** [comment]
> Örnek uygulama Compose ile oluşturulmuştur. Dolayısıyla, Compose görünümün ana bilgisayarıdır. Burada, `AndroidViewBinding`XML düzen kaynağını şişirir ve bağlamasını döndürür. Grafik görünümündeki tüm değişiklikler standart `android.view.View`stil API'leri kullanılarak yapılır ve Compose'u içermez.

It's quite complicated for someone like me who doesn't know how to compose. I wish there was a full XML format. Thank you

**Comment by Gowsky** [comment]
You can simply ignore the Compose part, as its irrelevant and it's used as a host for the view, just like a `Fragment`, or `Activity` would be. The XML code is there also in the standard `/res/layout` directory. And the styles are in `/res/values` directory.
